# Generated by Django 5.2.6 on 2025-09-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_gmail_address_user_gmail_app_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
