# Generated by Django 5.2.6 on 2025-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
